# Copyright (C) 2026 H. Blok
# SPDX-License-Identifier: GPL-3.0-or-later

"""TankBattle configuration constants."""

# Display
SCREEN_WIDTH = 640
SCREEN_HEIGHT = 480
FPS = 60
FULLSCREEN = True
VSYNC = True
WINDOW_TITLE = "Tank Battle"

# World
WORLD_WIDTH = 6400
WORLD_HEIGHT = 4800
TILE_SIZE = 32
WORLD_TILES_X = WORLD_WIDTH // TILE_SIZE
WORLD_TILES_Y = WORLD_HEIGHT // TILE_SIZE

# Tank
TANK_SPEED = 150.0
TANK_ROTATION_SPEED = 200.0
TURRET_ROTATION_SPEED = 240.0
DIAGONAL_SENSITIVITY = 1.3
TANK_MAX_HP = 10
TANK_HITBOX_RADIUS = 16.0
TANK_COLLISION_RADIUS = 15.0
TANK_HIT_FLASH_TIME = 0.2
TANK_DESTROY_ANIMATION_TIME = 0.8
TANK_BODY_WIDTH = 28
TANK_BODY_HEIGHT = 36
TANK_TURRET_WIDTH = 8
TANK_TURRET_HEIGHT = 28

# Input
JOYSTICK_DEADZONE = 0.15
DIAGONAL_NORMALIZER = 0.707
TURRET_INPUT_SMOOTHING = 0.3

# Network
HOST_PORT = 5555
DISCOVERY_PORT = 5556
GAME_DATA_PORT = 5557
DISCOVERY_MULTICAST_GROUP = "239.255.190.20"
NETWORK_UPDATE_HZ = 20
NETWORK_UPDATE_INTERVAL = 1.0 / NETWORK_UPDATE_HZ
DISCOVERY_BROADCAST_INTERVAL = 2.0
DISCOVERY_TIMEOUT = 10.0
RECONNECT_TIMEOUT = 10.0
MAX_PACKET_SIZE = 65536
PROTOCOL_VERSION = 1
BEACON_PREFIX = "TANKBATTLE_BEACON"
BEACON_RESPONSE = "TANKBATTLE_RESPONSE"
HANDSHAKE_PREFIX = "TANKBATTLE_HELLO"
WELCOME_PREFIX = "TANKBATTLE_WELCOME"
WELCOME_ACK_PREFIX = "TANKBATTLE_WELCOME_ACK"
PING_PREFIX = "TANKBATTLE_PING"
PING_INTERVAL = 2.0
HANDSHAKE_TIMEOUT = 5.0
HP_SYNC_INTERVAL = 3.0
CONNECTION_QUALITY_GOOD = 0.8
CONNECTION_QUALITY_POOR = 0.4

# Round
ROUND_COUNT = 4
ROUNDS_TO_WIN = 3
ROUND_TIME_LIMIT = 150.0
ROUND_OVER_TIME = 3.0
COUNTDOWN_TIME = 3.0
ROUND_END_INPUT_GRACE = 1.0   # seconds after end-screen entry before input is accepted
MATCH_OVER_TIMEOUT = 30.0     # auto-return to MENU if no action taken
SUDDEN_DEATH_DAMAGE = 10
MAX_DT = 0.05

# Power-ups
WEAPON_DURATION = 25.0
SPREAD_SHOT_COUNT = 3
SPREAD_SHOT_ANGLE = 15.0
SPREAD_SHOT_LIMIT = 30
ROCKET_SPEED = 200.0
ROCKET_DAMAGE = 3
ROCKET_RADIUS = 48.0
ROCKET_LIMIT = 5
RICOCHET_BOUNCES = 2
RICOCHET_LIMIT = 20
MINE_DAMAGE = 3
MINE_TRIGGER_RADIUS = 32.0
MINE_ARM_TIME = 1.5
MINE_LIMIT = 5
RAPID_FIRE_COOLDOWN = 0.1
PRIMARY_FIRE_COOLDOWN = 0.4
HEALTH_PACK_RESTORE = 4
POWERUP_SPAWN_INTERVAL_MIN = 8.0
POWERUP_SPAWN_INTERVAL_MAX = 15.0
POWERUP_MAX_ON_MAP = 5
POWERUP_COLLISION_RADIUS = 22.0
POWERUP_PULSE_SPEED = 4.0

# Bullet
BULLET_SPEED = 400.0
BULLET_DAMAGE = 1
BULLET_RADIUS = 4.0
BULLET_MAX_LIFETIME = 6.0

# Mine
MINE_RADIUS = 8.0

# Obstacles — reduced density for better gameplay on handhelds.
# Previous values (0.12–0.18 hard, 0.05–0.08 soft) resulted in
# 17–26 % of the 30 000 tiles being blocked, which felt cramped.
# New values target ~7–12 % hard and ~2–4 % soft.
HARD_ROCK_RATIO_MIN = 0.05
HARD_ROCK_RATIO_MAX = 0.08
SOFT_OBSTACLE_RATIO_MIN = 0.02
SOFT_OBSTACLE_RATIO_MAX = 0.04
SPAWN_CLEAR_RADIUS_TILES = 6
CENTER_CLEAR_RADIUS_TILES = 8
ROCK_CLUSTER_ATTEMPTS = 600
ROCK_CLUSTER_MIN_SIZE = 2
ROCK_CLUSTER_MAX_SIZE = 5
SOFT_RESTORE_VALUE = 1

# Spawn points
SPAWN_ONE_X = WORLD_WIDTH * 0.25
SPAWN_ONE_Y = WORLD_HEIGHT * 0.25
SPAWN_TWO_X = WORLD_WIDTH * 0.75
SPAWN_TWO_Y = WORLD_HEIGHT * 0.75

# HUD
HUD_HP_X = 12
HUD_HP_Y = 12
HUD_HP_SEGMENT_WIDTH = 14
HUD_HP_SEGMENT_HEIGHT = 10
HUD_HP_SEGMENT_GAP = 2
HUD_WEAPON_X = SCREEN_WIDTH // 2
HUD_WEAPON_Y = 14
HUD_ROUND_X = SCREEN_WIDTH - 39
HUD_ROUND_Y = 12
HUD_PIP_RADIUS = 6
HUD_MINIMAP_WIDTH = 100
HUD_MINIMAP_HEIGHT = 75
HUD_MINIMAP_X = SCREEN_WIDTH - HUD_MINIMAP_WIDTH - 10
HUD_MINIMAP_Y = SCREEN_HEIGHT - HUD_MINIMAP_HEIGHT - 10
HUD_MINIMAP_SCALE_X = HUD_MINIMAP_WIDTH / WORLD_WIDTH
HUD_MINIMAP_SCALE_Y = HUD_MINIMAP_HEIGHT / WORLD_HEIGHT
HUD_TIMER_Y = 36

# Connection status widget
HUD_CONN_X = SCREEN_WIDTH - 48
HUD_CONN_Y = 52
HUD_CONN_BAR_WIDTH = 6
HUD_CONN_BAR_HEIGHT = 18
HUD_CONN_BAR_GAP = 2
HUD_CONN_NUM_BARS = 4

# Colors
COLOR_BLACK = (0, 0, 0)
COLOR_WHITE = (255, 255, 255)
COLOR_GREY = (100, 100, 100)
COLOR_DARK_GREY = (45, 45, 45)
COLOR_LIGHT_GREY = (180, 180, 180)
COLOR_GREEN = (40, 220, 80)
COLOR_RED = (220, 60, 50)
COLOR_BLUE = (70, 130, 220)
COLOR_YELLOW = (240, 220, 60)
COLOR_ORANGE = (240, 140, 40)
COLOR_BG = (38, 74, 42)
COLOR_SOFT = (145, 105, 64)
COLOR_HARD = (55, 55, 60)
COLOR_WATER = (35, 75, 105)
COLOR_TRANSPARENT = (0, 0, 0, 0)
COLOR_DARK_GREEN = (20, 110, 40)
COLOR_DARK_RED = (110, 30, 25)
COLOR_TANK_GREEN_DARK = (20, 170, 60)
COLOR_TANK_RED_DARK = (170, 40, 35)
COLOR_TANK_GREEN_LIGHT = (80, 255, 120)
COLOR_TANK_RED_LIGHT = (255, 100, 90)
COLOR_NEUTRAL = (150, 150, 150)
COLOR_MENU_BG = (15, 15, 25)
COLOR_MENU_BORDER = (40, 100, 50)
COLOR_HUD_BG = (0, 0, 0, 120)

# Menu
MENU_ITEMS = ("Solo Practice", "Host Game", "Join Game", "Quit")

LOBBY_ITEMS = ("Start", "Manual IP", "Back")
MENU_FONT_SIZE = 34
HUD_FONT_SIZE = 20
SMALL_FONT_SIZE = 16
BIG_FONT_SIZE = 72


# AI (single-player)
AI_ENGAGE_DISTANCE = 300.0
AI_RETREAT_DISTANCE = 120.0
AI_AIM_TOLERANCE_DEG = 25.0
AI_FIRE_INTERVAL_MIN = 0.3
AI_FIRE_INTERVAL_MAX = 0.9

# Neutral AI tanks ("Wild Tanks")
NEUTRAL_TANK_COUNT = 2
NEUTRAL_TANK_HP = 2
NEUTRAL_TANK_SYNC_INTERVAL = 0.1

# Rendering
PARTICLE_MAX_COUNT = 200
EXPLOSION_PARTICLE_COUNT = 12
EXPLOSION_SPEED = 80.0
EXPLOSION_LIFETIME = 0.5
MUZZLE_FLASH_PARTICLE_COUNT = 5
SMOKE_PARTICLE_COUNT = 3
TANK_SHADOW_OFFSET = 3
POWERUP_GLOW_ALPHA = 40
DESTROYED_SMOKE_CHANCE = 0.1
