# Copyright (C) 2026 H. Blok
# SPDX-License-Identifier: GPL-3.0-or-later

"""TankBattle configuration constants."""

# Display
SCREEN_WIDTH = 640
SCREEN_HEIGHT = 480
FPS = 60
FULLSCREEN = True
VSYNC = True
WINDOW_TITLE = "Tank Battle"

# World
WORLD_WIDTH = 6400
WORLD_HEIGHT = 4800
TILE_SIZE = 32
WORLD_TILES_X = WORLD_WIDTH // TILE_SIZE
WORLD_TILES_Y = WORLD_HEIGHT // TILE_SIZE

# Tank
TANK_SPEED = 150.0
TANK_ROTATION_SPEED = 120.0
TANK_MAX_HP = 10
TANK_HITBOX_RADIUS = 16.0
TANK_COLLISION_RADIUS = 15.0
TANK_HIT_FLASH_TIME = 0.2
TANK_DESTROY_ANIMATION_TIME = 0.8
TANK_BODY_WIDTH = 28
TANK_BODY_HEIGHT = 36
TANK_TURRET_WIDTH = 8
TANK_TURRET_HEIGHT = 28

# Input
JOYSTICK_DEADZONE = 0.2
DIAGONAL_NORMALIZER = 0.707

# Network
HOST_PORT = 5555
UDP_BEACON_PORT = 5556
NETWORK_UPDATE_HZ = 20
NETWORK_UPDATE_INTERVAL = 1.0 / NETWORK_UPDATE_HZ
DISCOVERY_INTERVAL = 1.0
DISCOVERY_TIMEOUT = 3.0
RECONNECT_TIMEOUT = 10.0
MAX_PACKET_SIZE = 512
PROTOCOL_VERSION = 1
BEACON_PREFIX = "TANKBATTLE_BEACON"
HANDSHAKE_PREFIX = "TANKBATTLE_HELLO"

# Round
ROUND_COUNT = 3
ROUNDS_TO_WIN = 2
ROUND_TIME_LIMIT = 90.0
ROUND_OVER_TIME = 3.0
COUNTDOWN_TIME = 3.0
SUDDEN_DEATH_DAMAGE = 10
MAX_DT = 0.05

# Power-ups
WEAPON_DURATION = 25.0
SPREAD_SHOT_COUNT = 3
SPREAD_SHOT_ANGLE = 15.0
SPREAD_SHOT_LIMIT = 30
ROCKET_SPEED = 200.0
ROCKET_DAMAGE = 3
ROCKET_RADIUS = 48.0
ROCKET_LIMIT = 5
RICOCHET_BOUNCES = 2
RICOCHET_LIMIT = 20
MINE_DAMAGE = 3
MINE_TRIGGER_RADIUS = 32.0
MINE_ARM_TIME = 1.5
MINE_LIMIT = 5
RAPID_FIRE_COOLDOWN = 0.1
PRIMARY_FIRE_COOLDOWN = 0.4
HEALTH_PACK_RESTORE = 4
POWERUP_SPAWN_INTERVAL_MIN = 8.0
POWERUP_SPAWN_INTERVAL_MAX = 15.0
POWERUP_MAX_ON_MAP = 5
POWERUP_COLLISION_RADIUS = 22.0
POWERUP_PULSE_SPEED = 4.0

# Bullet
BULLET_SPEED = 400.0
BULLET_DAMAGE = 1
BULLET_RADIUS = 4.0
BULLET_MAX_LIFETIME = 6.0

# Mine
MINE_RADIUS = 8.0

# Obstacles
HARD_ROCK_RATIO_MIN = 0.12
HARD_ROCK_RATIO_MAX = 0.18
SOFT_OBSTACLE_RATIO_MIN = 0.05
SOFT_OBSTACLE_RATIO_MAX = 0.08
SPAWN_CLEAR_RADIUS_TILES = 4
CENTER_CLEAR_RADIUS_TILES = 8
ROCK_CLUSTER_ATTEMPTS = 1200
ROCK_CLUSTER_MIN_SIZE = 3
ROCK_CLUSTER_MAX_SIZE = 8
SOFT_RESTORE_VALUE = 1

# Spawn points
SPAWN_ONE_X = WORLD_WIDTH * 0.25
SPAWN_ONE_Y = WORLD_HEIGHT * 0.25
SPAWN_TWO_X = WORLD_WIDTH * 0.75
SPAWN_TWO_Y = WORLD_HEIGHT * 0.75

# HUD
HUD_HP_X = 12
HUD_HP_Y = 12
HUD_HP_SEGMENT_WIDTH = 14
HUD_HP_SEGMENT_HEIGHT = 10
HUD_HP_SEGMENT_GAP = 2
HUD_WEAPON_X = SCREEN_WIDTH // 2
HUD_WEAPON_Y = 14
HUD_ROUND_X = SCREEN_WIDTH - 92
HUD_ROUND_Y = 12
HUD_PIP_RADIUS = 6
HUD_MINIMAP_WIDTH = 100
HUD_MINIMAP_HEIGHT = 75
HUD_MINIMAP_X = SCREEN_WIDTH - HUD_MINIMAP_WIDTH - 10
HUD_MINIMAP_Y = SCREEN_HEIGHT - HUD_MINIMAP_HEIGHT - 10
HUD_MINIMAP_SCALE_X = HUD_MINIMAP_WIDTH / WORLD_WIDTH
HUD_MINIMAP_SCALE_Y = HUD_MINIMAP_HEIGHT / WORLD_HEIGHT
HUD_TIMER_Y = 36

# Colors
COLOR_BLACK = (0, 0, 0)
COLOR_WHITE = (255, 255, 255)
COLOR_GREY = (100, 100, 100)
COLOR_DARK_GREY = (45, 45, 45)
COLOR_LIGHT_GREY = (180, 180, 180)
COLOR_GREEN = (40, 220, 80)
COLOR_RED = (220, 60, 50)
COLOR_BLUE = (70, 130, 220)
COLOR_YELLOW = (240, 220, 60)
COLOR_ORANGE = (240, 140, 40)
COLOR_BG = (38, 74, 42)
COLOR_SOFT = (145, 105, 64)
COLOR_HARD = (55, 55, 60)
COLOR_WATER = (35, 75, 105)
COLOR_TRANSPARENT = (0, 0, 0, 0)

# Menu
MENU_ITEMS = ("Host Game", "Join Game", "Quit")
LOBBY_ITEMS = ("Start", "Manual IP", "Back")
MENU_FONT_SIZE = 34
HUD_FONT_SIZE = 20
SMALL_FONT_SIZE = 16
BIG_FONT_SIZE = 72
