# Copyright (C) 2025 H. Blok
# SPDX-License-Identifier: GPL-3.0-or-later

py_library(
    name = "common",
    srcs = ["compat_sdl.py"],
    data = ["version.json"],
    visibility = ["//visibility:public"],
)