py_test(
    name = "test_utils",
    srcs = ["test_utils.py"],
    deps = [
        "//maxbloks/mathwheel",
    ],
    size = "small",
)

py_test(
    name = "test_entities",
    srcs = ["test_entities.py"],
    deps = [
        "//maxbloks/mathwheel",
    ],
    size = "small",
)

py_test(
    name = "test_constants",
    srcs = ["test_constants.py"],
    deps = [
        "//maxbloks/mathwheel",
    ],
    size = "small",
)