py_test(
    name = "test_background",
    srcs = ["test_background.py"],
    deps = [
        "//maxbloks/dogrider",
    ],
    size = "small",
)

py_test(
    name = "test_constants",
    srcs = ["test_constants.py"],
    deps = [
        "//maxbloks/dogrider",
    ],
    size = "small",
)

py_test(
    name = "test_dog_rider",
    srcs = ["test_dog_rider.py"],
    deps = [
        "//maxbloks/dogrider",
    ],
    size = "small",
)

py_test(
    name = "test_obstacles",
    srcs = ["test_obstacles.py"],
    deps = [
        "//maxbloks/dogrider",
    ],
    size = "small",
)

py_test(
    name = "test_game_framework",
    srcs = ["test_game_framework.py"],
    deps = [
        "//maxbloks/dogrider",
    ],
    size = "small",
)
