py_library(
    name = "ui",
    srcs = [
        "__init__.py",
        "button_hints.py",
        "command_builder.py",
        "confirm_dialog.py",
        "font_manager.py",
        "output_display.py",
        "scrollable_list.py",
        "virtual_keyboard.py",
    ],
    deps = [
        "//maxbloks/terminal/config:config",
	"@games_pip_deps//pygame_ce",
    ],
    visibility = ["//visibility:public"],
)