# Copyright (C) 2025 H. Blok
# SPDX-License-Identifier: GPL-3.0-or-later

load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "test_camera",
    srcs = ["test_camera.py"],
    deps = ["//maxbloks/tanks", "@games_pip_deps//pygame_ce"],
)

py_test(
    name = "test_collision",
    srcs = ["test_collision.py"],
    deps = ["//maxbloks/tanks", "@games_pip_deps//pygame_ce"],
)

py_test(
    name = "test_config",
    srcs = ["test_config.py"],
    deps = ["//maxbloks/tanks", "@games_pip_deps//pygame_ce"],
)

py_test(
    name = "test_entities",
    srcs = ["test_entities.py"],
    deps = ["//maxbloks/tanks", "@games_pip_deps//pygame_ce"],
)

py_test(
    name = "test_game_state",
    srcs = ["test_game_state.py"],
    deps = ["//maxbloks/tanks", "@games_pip_deps//pygame_ce"],
)

py_test(
    name = "test_game_unit",
    srcs = ["test_game_unit.py"],
    deps = ["//maxbloks/tanks", "@games_pip_deps//pygame_ce"],
)

py_test(
    name = "test_input_handler",
    srcs = ["test_input_handler.py"],
    deps = ["//maxbloks/tanks", "@games_pip_deps//pygame_ce"],
)

py_test(
    name = "test_integration",
    srcs = ["test_integration.py"],
    deps = ["//maxbloks/tanks", "@games_pip_deps//pygame_ce"],
)

py_test(
    name = "test_obstacles",
    srcs = ["test_obstacles.py"],
    deps = ["//maxbloks/tanks", "@games_pip_deps//pygame_ce"],
)

py_test(
    name = "test_paths",
    srcs = ["test_paths.py"],
    deps = ["//maxbloks/tanks", "@games_pip_deps//pygame_ce"],
)

py_test(
    name = "test_render",
    srcs = ["test_render.py"],
    deps = ["//maxbloks/tanks", "@games_pip_deps//pygame_ce"],
)

py_test(
    name = "test_spawner",
    srcs = ["test_spawner.py"],
    deps = ["//maxbloks/tanks", "@games_pip_deps//pygame_ce"],
)

py_test(
    name = "test_ui",
    srcs = ["test_ui.py"],
    deps = ["//maxbloks/tanks", "@games_pip_deps//pygame_ce"],
)

py_test(
    name = "test_weapon_manager",
    srcs = ["test_weapon_manager.py"],
    deps = ["//maxbloks/tanks", "@games_pip_deps//pygame_ce"],
)

py_test(
    name = "test_weapons",
    srcs = ["test_weapons.py"],
    deps = ["//maxbloks/tanks", "@games_pip_deps//pygame_ce"],
)

py_test(
    name = "test_world",
    srcs = ["test_world.py"],
    deps = ["//maxbloks/tanks", "@games_pip_deps//pygame_ce"],
)
