# Copyright (C) 2026 H. Blok
# SPDX-License-Identifier: GPL-3.0-or-later

load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "test_entities",
    srcs = ["test_entities.py"],
    deps = ["//maxbloks/dune", "@games_pip_deps//pygame_ce"],
    size = "small",
)

py_test(
    name = "test_constants",
    srcs = ["test_constants.py"],
    deps = ["//maxbloks/dune", "@games_pip_deps//pygame_ce"],
    size = "small",
)

py_test(
    name = "test_utils",
    srcs = ["test_utils.py"],
    deps = ["//maxbloks/dune", "@games_pip_deps//pygame_ce"],
    size = "small",
)

py_test(
    name = "test_game",
    srcs = ["test_game.py"],
    deps = ["//maxbloks/dune", "@games_pip_deps//pygame_ce"],
    size = "small",
)
