py_library(
    name = "core",
    srcs = glob(["*.py"]),
    deps = [
        "//maxbloks/terminal/config:config",
        "//maxbloks/terminal/ui:ui",
    ],
    visibility = ["//visibility:public"],
)