py_library(
    name = "core",
    srcs = [
        "command_executor.py",
        "terminal_editor.py",
    ],
    deps = [
        "//maxbloks/terminal/config:config",
        "//maxbloks/terminal/ui:ui",
    ],
    visibility = ["//visibility:public"],
)