# Copyright (C) 2026 H. Blok
# SPDX-License-Identifier: GPL-3.0-or-later

py_test(
    name = "test_constants",
    srcs = ["test_constants.py"],
    deps = ["//maxbloks/spellwheels"],
    size = "small",
)

py_test(
    name = "test_utils",
    srcs = ["test_utils.py"],
    deps = ["//maxbloks/spellwheels"],
    size = "small",
)

py_test(
    name = "test_entities",
    srcs = ["test_entities.py"],
    deps = ["//maxbloks/spellwheels"],
    size = "small",
)

py_test(
    name = "test_game",
    srcs = ["test_game.py"],
    deps = ["//maxbloks/spellwheels"],
    size = "small",
)