py_library(
    name = "terminal",
    srcs = [
        "main.py",
    ],
    deps = [
        "//maxbloks/terminal/config",
        "//maxbloks/terminal/core",
        "//maxbloks/terminal/ui",
    ],
    visibility = ["//visibility:public"],
)