# Copyright (C) 2026 H. Blok
# SPDX-License-Identifier: GPL-3.0-or-later

load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "test_ai",
    srcs = ["test_ai.py"],
    deps = ["//maxbloks/tankbattle", "@games_pip_deps//pygame_ce"],
    size = "small",
)

py_test(
    name = "test_arena",
    srcs = ["test_arena.py"],
    deps = ["//maxbloks/tankbattle", "@games_pip_deps//pygame_ce"],
    size = "small",
)

py_test(
    name = "test_entities",
    srcs = ["test_entities.py"],
    deps = ["//maxbloks/tankbattle", "@games_pip_deps//pygame_ce"],
    size = "small",
)

py_test(
    name = "test_network_connection_monitor",
    srcs = ["test_network_connection_monitor.py"],
    deps = ["//maxbloks/tankbattle", "@games_pip_deps//pygame_ce"],
    size = "small",
)

py_test(
    name = "test_network_dead_reckoner",
    srcs = ["test_network_dead_reckoner.py"],
    deps = ["//maxbloks/tankbattle", "@games_pip_deps//pygame_ce"],
    size = "small",
)

py_test(
    name = "test_network_discovery",
    srcs = ["test_network_discovery.py"],
    deps = ["//maxbloks/tankbattle", "@games_pip_deps//pygame_ce"],
    size = "small",
)

py_test(
    name = "test_network_packet",
    srcs = ["test_network_packet.py"],
    deps = ["//maxbloks/tankbattle", "@games_pip_deps//pygame_ce"],
    size = "small",
)

py_test(
    name = "test_utils",
    srcs = ["test_utils.py"],
    deps = ["//maxbloks/tankbattle", "@games_pip_deps//pygame_ce"],
    size = "small",
)

py_test(
    name = "test_game",
    srcs = ["test_game.py"],
    deps = ["//maxbloks/tankbattle", "@games_pip_deps//pygame_ce"],
    size = "small",
)

py_test(
    name = "test_hud",
    srcs = ["test_hud.py"],
    deps = ["//maxbloks/tankbattle", "@games_pip_deps//pygame_ce"],
    size = "small",
)

py_test(
    name = "test_input",
    srcs = ["test_input.py"],
    deps = ["//maxbloks/tankbattle", "@games_pip_deps//pygame_ce"],
    size = "small",
)

py_test(
    name = "test_network_manager",
    srcs = ["test_network_manager.py"],
    deps = ["//maxbloks/tankbattle", "@games_pip_deps//pygame_ce"],
    size = "small",
)

py_test(
    name = "test_rendering_particle_system",
    srcs = ["test_rendering_particle_system.py"],
    deps = ["//maxbloks/tankbattle", "@games_pip_deps//pygame_ce"],
    size = "small",
)

py_test(
    name = "test_rendering_renderer",
    srcs = ["test_rendering_renderer.py"],
    deps = ["//maxbloks/tankbattle", "@games_pip_deps//pygame_ce"],
    size = "small",
)

py_test(
    name = "test_rendering_sprite_cache",
    srcs = ["test_rendering_sprite_cache.py"],
    deps = ["//maxbloks/tankbattle", "@games_pip_deps//pygame_ce"],
    size = "small",
)
